### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dobbse42** [dobbse42/arithmetic#1]
- [x] write ctrladd function
- [x] move qubit creation to separate function
- [x] fix ancillary qubit location
- [x] write pseudocode for the multiplier
- [x] implement pseudocode
- [x] write testing code (displays two summands and sum, two factors and product)

Questions:
- Should buffer zeroes be added in the implementation by the user or by the multiplier/adder themselves?
- Should I move the toffoli step in the multiplier to it's own class as I did the adder?
- What is the standard on using moments (e.g. for the toffolis) versus simply appending a circuit to another?
